---
title: Goldhirsh Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Blog
    output: true
  capital:
    title: Capital
    output: false
    permalink: "/capital/:year/:month/:day/:title/"
  initiatives:
    title: Initiatives
    output: false
    permalink: "/initiatives/:year/:month/:day/:title/"
  jobs:
    title: Jobs
    output: false
    permalink: "/jobs/:year/:month/:day/:title/"
  opportunities:
    title: Opportunities
    output: false
    permalink: "/opportunities/:year/:month/:day/:title/"
  press:
    title: Press
    output: false
    permalink: "/press/:year/:month/:day/:title/"
  speaking:
    title: Speaking
    output: false
    permalink: "/speaking/:year/:month/:day/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    excerpt: ''
    author: Tara Roth
    layout: post
- scope:
    path: ''
    type: capital
  values:
    details_url: ''
    project: ''
    layout: default
- scope:
    path: ''
    type: initiatives
  values:
    details_url: ''
    layout: default
- scope:
    path: ''
    type: jobs
  values:
    details_url: ''
    organization: ''
    employment_type: ''
    location: ''
    layout: default
- scope:
    path: ''
    type: opportunities
  values:
    details_url: ''
    layout: default
- scope:
    path: ''
    type: press
  values:
    details_url: ''
    layout: default
- scope:
    path: ''
    type: speaking
  values:
    details_url: ''
    layout: default
exclude:
- README
permalink: pretty
