---
title: Goldhirsh Foundation
timezone: America/Los_Angeles
collections:
  jobs:
    title: Jobs
    output: false
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: jobs
  values:
    job_url: ''
    organization: ''
    employment_type: ''
    location: ''
    layout: default
- scope:
    path: ''
    type: press
  values:
    press_url: ''
    layout: default
exclude:
- README
permalink: pretty
