---
title: Goldhirsh Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Blog
    output: true
  jobs:
    title: Jobs
    output: false
  blog:
    title: Jobs
    output: false
  press:
    title: Press
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: press
  values:
    press_url: ''
    layout: default
- scope:
    path: ''
    type: blog
  values:
    author: Tara Roth
    layout: default
- scope:
    path: ''
    type: jobs
  values:
    job_url: ''
    organization: ''
    employment_type: ''
    location: ''
    layout: default
exclude:
- README
permalink: pretty
