---
title: Goldhirsh Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Blog
    output: true
  jobs:
    title: Jobs
    output: false
    permalink: "/jobs/:year/:month/:day/:title/"
  press:
    title: Press
    output: false
    permalink: "/press/:year/:month/:day/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: press
  values:
    press_url: ''
    layout: default
- scope:
    path: ''
    type: posts
  values:
    author: Tara Roth
    excerpt: ''
    layout: default
- scope:
    path: ''
    type: jobs
  values:
    job_url: ''
    organization: ''
    employment_type: ''
    location: ''
    layout: default
exclude:
- README
permalink: pretty
