---
title: Goldhirsh Foundation
timezone: UTC
collections:
  jobs:
    title: Jobs
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: jobs
  values:
    url: ''
    organization: ''
    employment_type: ''
    date_posted: ''
    location: ''
    layout: default
exclude:
- README
permalink: pretty
